### ISSUE TITLE
NSWAG OAS Generated Code Retains "," in enumeration value types

### ISSUE THREAD

**Issue by sjefvanleeuwen** [RSuter/NSwag#1611]
### Yaml

https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/BRPB1.0.yaml

```yaml
Naamgebruik:
      type: "string"
      enum:
      - "Eigen"
      - "Partner"
      - "Partner, eigen"
      - "Eigen, partner"
      description: "De voorgedefinieerde waarden van naamgebruik volgens de centrale\
        \ voorzieningen. Zie attribuut Naamgebruik van groep A.1.12 Naamgebruik van\
        \ BRP."
```
### Generates
```csharp
    public enum Naamgebruik
    {
        [System.Runtime.Serialization.EnumMember(Value = "Eigen")]
        Eigen = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "Partner")]
        Partner = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "Partner, eigen")]
        Partner,_eigen = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "Eigen, partner")]
        Eigen,_partner = 3,
    
    }
```
