### ISSUE TITLE
Invalid query parameter property emitted: nullable

### ISSUE THREAD

**Issue by wshirey** [RSuter/NSwag#1732]
The following controller action and model 
```csharp
public class GetPetListRequest : IRequest<GetPetListResponse>
{
  public bool enabled { get; set; } = true;

  [Required]
  public string name { get; set; }

  [Required]
  public string description { get; set; }
}

[Route("/[controller]")]
public class Pets
{
    public async Task<GetPetListResponse> ListPets([FromQuery] GetPetListRequest request)
    {
    ...
    }
}
```
produces this non-compliant OpenAPI snippet

```yaml
/Pets:
  get:
    ...      
    parameters:
    - name: enabled
      in: query
      schema:
        type: boolean
      nullable: false
    - name: name
      in: query
      required: true
      schema:
        type: string
      nullable: false
    - name: description
      in: query
      required: true
      schema:
        type: string
      nullable: false
```

The `nullable` properties are not compliant with OpenAPI 3.0.0.
