### ISSUE TITLE
Max/MinLength attributes for String field is missed

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#1833]
For next OpenApi 3.0.0 
```yaml
components:
  schemas:
    info:
      type: object
      properties:
        country:
          type: string
          minLength: 3
          maxLength: 3
```
last NSwag.MSBuild 12.0.7 not set `DataAnnotation` attributes:
```c#
[Newtonsoft.Json.JsonProperty("country", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public string Country { get; set; }
```
expect
```c#
[Newtonsoft.Json.JsonProperty("country", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
[MaxLength(3)]
[MinLength(3)]
public string Country { get; set; }
```
