### ISSUE TITLE
OpenAPI referenced type missed attributes

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#1835]
Whe i use property definition as reference in OpenAPI 3.0.0
```yaml
applicantIdDocs:
  type: object
  properties:
    country:
      $ref: '#/components/schemas/countryCode'
countryCode:
  type: string
  nullable: true
  maxLength: 3
  minLength: 3
```
then i get wrong code
```c#
[Newtonsoft.Json.JsonProperty("country", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public string Country { get; set; }
```
missed DataContract attributes, wrong JsonProperty(Required).

But in the same time, this explicit declaration
```yaml
applicantIdDocs:
  type: object
  properties:
    country:
      type: string
      nullable: true
      minLength: 3
      maxLength: 3
```
produce correct code with necessary attributes
```c#
[Newtonsoft.Json.JsonProperty("country", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
[System.ComponentModel.DataAnnotations.StringLength(3, MinimumLength = 3)]
public string Country { get; set; }
```
