### ISSUE TITLE
Default values not working for integer types?

### ISSUE THREAD

**Issue by plk** [RSuter/NSwag#1879]
I have `generateDefaultValues = true` which is working fine for complex types/enums etc. but for plain integers like:

```
someparam:
  type: integer
  default: 4
```

No default value is generated?

**Comment by plk** [comment]
Ok, it is required to have an explicit format:

```
someparam:
  type: integer
  format: int32
  default: 4
```
